name: main example
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 211408
          schedule-id: 100003
          seat-id: 678
          slack-incoming-webhook-url: ${{ secrets.https://hooks.slack.com/services/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 }}
          message: '<@4x8xvvfbty> ë‹¬ë ¤ë‹¬ë ¤~'ğŸš¨ Melon Ticket cancellation found! [ProdID: 211408] 7ì›” 6ì¼ 1ì¸µ 8êµ¬ì—­(678)ì´ ì—´ë ¸ìŠµë‹ˆë‹¤! \\ní‹°ì¼“ ë°”ë¡œê°€ê¸°: https://ticket.melon.com/performance/index.htm?prodId=211408&scheduleId=100003"
